(async()=>{
 const config=await fetch('config/default.json').then(r=>r.json());
 const paletteMenu=await fetch('config/palettes.json').then(r=>r.json());
 const canvas=document.querySelector('#canvas'),wrap=document.querySelector('#canvas-wrap'),ctx=canvas.getContext('2d',{willReadFrequently:true});
 document.querySelector('#studio-title').textContent=config.name==='Alice Studio'?'Shit Krita':(config.name||'Shit Krita');
 const STORAGE_KEY=config.storageKey||'alice-studio-autosave', background=config.background||'#fff';
 let tool='pencil',texture='solid',colour=config.defaultColour||'#252321',width=config.defaultWidth||5,drawing=false,last=null,lastTouchTime=0,dotDistance=0;
 const DOT_PENCIL_MODE='stroke'; // 'stroke' is live; 'reveal' preserves the original scratch-card behaviour for later mischief.
 const history=[], HISTORY_LIMIT=20, palette=document.querySelector('#palette'), paletteSelect=document.querySelector('#palette-select');
 const widths=document.querySelector('#widths');
 (config.widths||[1.5,5,14]).forEach(w=>{const b=document.createElement('button');b.className='width'+(w===width?' active':'');b.dataset.width=w;b.type='button';b.setAttribute('aria-label',`${w} pixel line`);const d=document.createElement('span');d.className='dot';d.style.width=d.style.height=Math.max(4,Math.min(16,w+3))+'px';b.appendChild(d);widths.appendChild(b)});
 paletteMenu.palettes.forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;paletteSelect.appendChild(o)});
 async function loadPalette(id){const entry=paletteMenu.palettes.find(p=>p.id===id)||paletteMenu.palettes[0],data=await fetch('config/'+entry.file).then(r=>r.json());palette.innerHTML='';data.colours.forEach((c,i)=>{const b=document.createElement('button');b.className='swatch'+(i===0?' active':'');b.dataset.colour=c.hex;b.style.setProperty('--swatch',c.hex);b.type='button';b.setAttribute('aria-label',c.name||c.hex);b.onclick=()=>{colour=b.dataset.colour;activate('.swatch',b)};palette.appendChild(b)});colour=data.colours[0].hex;paletteSelect.value=entry.id;try{localStorage.setItem('alice-studio-palette',entry.id)}catch{}}
 let initialPalette=paletteMenu.default;try{initialPalette=localStorage.getItem('alice-studio-palette')||initialPalette}catch{}await loadPalette(initialPalette);paletteSelect.onchange=()=>loadPalette(paletteSelect.value);
 function cssSize(){const r=wrap.getBoundingClientRect(),pad=innerWidth<=760?12:32;return{w:Math.max(1,r.width-pad),h:Math.max(1,r.height-pad)}}
 function fillBackground(){const{w,h}=cssSize();ctx.fillStyle=background;ctx.fillRect(0,0,w,h)}
 function resizeCanvas(preserve=true){const{w,h}=cssSize(),dpr=Math.max(1,devicePixelRatio||1),old=document.createElement('canvas');old.width=canvas.width;old.height=canvas.height;if(preserve&&canvas.width)old.getContext('2d').drawImage(canvas,0,0);canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.lineCap='round';ctx.lineJoin='round';fillBackground();if(preserve&&old.width)ctx.drawImage(old,0,0,old.width,old.height,0,0,w,h)}
 function point(x,y){const r=canvas.getBoundingClientRect();return{x:x-r.left,y:y-r.top}}
 function snapshot(){try{history.push(canvas.toDataURL('image/png'));if(history.length>HISTORY_LIMIT)history.shift()}catch{}}
 function saveLocal(){try{localStorage.setItem(STORAGE_KEY,canvas.toDataURL('image/png'))}catch{}}
 function restore(data){const img=new Image();img.onload=()=>{const{w,h}=cssSize();ctx.clearRect(0,0,w,h);fillBackground();ctx.drawImage(img,0,0,w,h);saveLocal()};img.src=data}
 function undo(){const p=history.pop();if(p)restore(p)}
 function dotSpec(){if(width<=2)return{spacing:4,radius:.8};if(width<=7)return{spacing:7,radius:1.5};return{spacing:12,radius:3}}
 function dotPattern(){const s=dotSpec(),dpr=Math.max(1,devicePixelRatio||1),tile=document.createElement('canvas');tile.width=Math.max(1,Math.round(s.spacing*dpr));tile.height=tile.width;const t=tile.getContext('2d');t.scale(dpr,dpr);t.fillStyle=colour;t.beginPath();t.arc(s.spacing/2,s.spacing/2,s.radius,0,Math.PI*2);t.fill();return ctx.createPattern(tile,'repeat')}
 function drawReveal(a,b){ctx.globalCompositeOperation='source-over';ctx.strokeStyle=dotPattern();ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
 function strokeDotSpec(){if(width<=2)return{spacing:4,radius:1};if(width<=7)return{spacing:8,radius:2.5};return{spacing:19,radius:7}}
 function stampDot(x,y){const s=strokeDotSpec();ctx.globalCompositeOperation='source-over';ctx.fillStyle=colour;ctx.beginPath();ctx.arc(x,y,s.radius,0,Math.PI*2);ctx.fill()}
 function drawDots(a,b){const s=strokeDotSpec(),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy);if(!len)return;let d=s.spacing-dotDistance;if(d<0.001)d=s.spacing;while(d<=len){const t=d/len;stampDot(a.x+dx*t,a.y+dy*t);d+=s.spacing}dotDistance=(dotDistance+len)%s.spacing}
 function draw(a,b){if(tool==='eraser'){ctx.globalCompositeOperation='source-over';ctx.strokeStyle=background;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();return}if(texture==='dots'){if(DOT_PENCIL_MODE==='reveal')drawReveal(a,b);else drawDots(a,b);return}ctx.globalCompositeOperation='source-over';ctx.strokeStyle=colour;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
 function floodFill(p){const dpr=Math.max(1,devicePixelRatio||1),x=Math.floor(p.x*dpr),y=Math.floor(p.y*dpr),w=canvas.width,h=canvas.height;if(x<0||y<0||x>=w||y>=h)return;const img=ctx.getImageData(0,0,w,h),data=img.data,start=(y*w+x)*4,target=[data[start],data[start+1],data[start+2],data[start+3]],temp=document.createElement('canvas').getContext('2d');temp.fillStyle=colour;temp.fillRect(0,0,1,1);const fill=temp.getImageData(0,0,1,1).data;if(texture==='solid'&&target[0]===fill[0]&&target[1]===fill[1]&&target[2]===fill[2])return;const match=i=>Math.abs(data[i]-target[0])<12&&Math.abs(data[i+1]-target[1])<12&&Math.abs(data[i+2]-target[2])<12&&data[i+3]===target[3],stack=[[x,y]],filled=new Uint8Array(w*h);while(stack.length){const[cx,cy]=stack.pop();if(cx<0||cy<0||cx>=w||cy>=h)continue;const pos=cy*w+cx;if(filled[pos])continue;const i=pos*4;if(!match(i))continue;filled[pos]=1;stack.push([cx+1,cy],[cx-1,cy],[cx,cy+1],[cx,cy-1])}
 if(texture==='dots'){const s=dotSpec(),spacing=Math.max(2,Math.round(s.spacing*dpr)),radius=Math.max(1,s.radius*dpr),r2=radius*radius;for(let cy=0;cy<h;cy++)for(let cx=0;cx<w;cx++){if(!filled[cy*w+cx])continue;const dx=((cx-spacing/2)%spacing+spacing)%spacing-spacing/2,dy=((cy-spacing/2)%spacing+spacing)%spacing-spacing/2;if(dx*dx+dy*dy<=r2){const i=(cy*w+cx)*4;data[i]=fill[0];data[i+1]=fill[1];data[i+2]=fill[2];data[i+3]=255}}ctx.putImageData(img,0,0);return}
 for(let pos=0;pos<filled.length;pos++)if(filled[pos]){const i=pos*4;data[i]=fill[0];data[i+1]=fill[1];data[i+2]=fill[2];data[i+3]=255}const radius=Math.max(2,Math.round(width*dpr/2+3*dpr)),boundary=[];for(let cy=0;cy<h;cy++)for(let cx=0;cx<w;cx++){const pos=cy*w+cx;if(filled[pos]&&(cx===0||cy===0||cx===w-1||cy===h-1||!filled[pos-1]||!filled[pos+1]||!filled[pos-w]||!filled[pos+w]))boundary.push([cx,cy])}for(const[bx,by]of boundary)for(let oy=-radius;oy<=radius;oy++)for(let ox=-radius;ox<=radius;ox++){if(ox*ox+oy*oy>radius*radius)continue;const px=bx+ox,py=by+oy;if(px<0||py<0||px>=w||py>=h)continue;const i=(py*w+px)*4;data[i]=fill[0];data[i+1]=fill[1];data[i+2]=fill[2];data[i+3]=255}ctx.putImageData(img,0,0)}
 function begin(p){snapshot();if(tool==='fill'){floodFill(p);saveLocal();return}drawing=true;last=p;dotDistance=0;if(tool==='pencil'&&texture==='dots'&&DOT_PENCIL_MODE==='stroke')stampDot(p.x,p.y);else draw(last,last)}function move(p){if(drawing){draw(last,p);last=p}}function finish(){if(!drawing)return;drawing=false;last=null;dotDistance=0;saveLocal()}
 function activate(sel,el){document.querySelectorAll(sel).forEach(b=>b.classList.remove('active'));if(el)el.classList.add('active')}
 document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{tool=b.dataset.tool;activate('.tool',b)});document.querySelectorAll('.width').forEach(b=>b.onclick=()=>{width=+b.dataset.width;activate('.width',b)});document.querySelectorAll('.texture').forEach(b=>b.onclick=()=>{texture=b.dataset.texture;activate('.texture',b)});
 document.querySelector('#undo').onclick=undo;document.querySelector('#clear').onclick=()=>{snapshot();const{w,h}=cssSize();ctx.clearRect(0,0,w,h);fillBackground();try{localStorage.removeItem(STORAGE_KEY)}catch{}};
 document.querySelector('#save').onclick=async()=>{const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)return;const file=new File([blob],config.exportFilename||'shit-krita.png',{type:'image/png'});if(navigator.canShare&&navigator.canShare({files:[file]})&&navigator.share){try{await navigator.share({files:[file],title:'Shit Krita'});return}catch(e){if(e.name==='AbortError')return}}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 canvas.addEventListener('touchstart',e=>{e.preventDefault();lastTouchTime=Date.now();const t=e.changedTouches[0];if(t)begin(point(t.clientX,t.clientY))},{passive:false});canvas.addEventListener('touchmove',e=>{e.preventDefault();lastTouchTime=Date.now();const t=e.changedTouches[0];if(t)move(point(t.clientX,t.clientY))},{passive:false});canvas.addEventListener('touchend',e=>{e.preventDefault();lastTouchTime=Date.now();finish()},{passive:false});canvas.addEventListener('touchcancel',e=>{e.preventDefault();finish()},{passive:false});
 if(window.PointerEvent){canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;e.preventDefault();begin(point(e.clientX,e.clientY));try{canvas.setPointerCapture(e.pointerId)}catch{}},{passive:false});canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!drawing)return;e.preventDefault();move(point(e.clientX,e.clientY))},{passive:false});canvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch')return;e.preventDefault();finish()},{passive:false})}
 canvas.addEventListener('mousedown',e=>{if(Date.now()-lastTouchTime<700)return;e.preventDefault();begin(point(e.clientX,e.clientY))});window.addEventListener('mousemove',e=>{if(drawing&&Date.now()-lastTouchTime>=700)move(point(e.clientX,e.clientY))});window.addEventListener('mouseup',()=>{if(Date.now()-lastTouchTime>=700)finish()});canvas.addEventListener('contextmenu',e=>e.preventDefault());
 resizeCanvas(false);try{const saved=localStorage.getItem(STORAGE_KEY);if(saved){const img=new Image();img.onload=()=>{const{w,h}=cssSize();ctx.drawImage(img,0,0,w,h)};img.src=saved}}catch{}let timer;addEventListener('resize',()=>{clearTimeout(timer);timer=setTimeout(()=>resizeCanvas(true),160)});
})();
